name: 🚀 Deploy Next.js to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.STAGING_VPS_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_VPS_USER }}@${{ secrets.STAGING_VPS_HOST }} << 'EOF'
            cd /var/www/keystoneability.com
            git pull origin main
            npm install
            npm run build
            pm2 restart nextjs-production || PORT=3001 pm2 start npm --name "nextjs-production" -- start
            pm2 save
          EOF
